### ISSUE TITLE
download data

### ISSUE THREAD

**Issue by lahirujayakody** [wateraccounting/WAPORWA#7]
Can you explain how can I download and create required data (data that downloaded from ftp://ftp.wateraccounting.unesco-ihe.org/WaterAccounting_Guest/Github_data/WAPORWA/Global.rar)

**Comment by trngbich** [comment]
Hi. usually you can open the link in web browser, but currently, it doesn't seem to work.
You can access the FTP site using FileZilla (https://filezilla-project.org/).
Host: ftp.wateraccounting.unesco-ihe.org
Username: wateraccountingguest
Password: W@t3r@ccounting

**Comment by lahirujayakody** [comment]
Thank You
